config/routes.rb
Tanmer::Application.routes.draw do
  resources :page_images do 
    collection {post :upload}
  end

  mount Ckeditor::Engine => '/ckeditor'
  get "members/index"
  get "members/show"
  get "members/edit"
  get "members/update"
  get "members/destroy"
  resources :page_rates

  devise_for :members
  resources :books
  resources :keystores

  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks"}
  #match '/users/auth/:provider/callback', to: "omniauth_callbacks#all", via: :get

  # devise_scope :users do
  #   get "/auth/:provider/callback" => "omniauth_callbacks_controller#all"
  # end

  resources :users do
    resources :pages
    resources :members
  end

  #match home search/case special path
  match '/search(/page/:page)', to: "home#search", via: :get, as: 'search'
  match '/case(/page/:page)', to: "home#case", via: :get, as: 'case'
  #tag
  match '/users/:user_id/tag/:tag(/page/:page)', to: "pages#tag", via: :get, as: 'tag'

  #short url
  match '/u/:user_id', to: "pages#index", via: :get
  #match '/:user_id/:id', to: "pages#show", via: :get

  match '/p/u:user_id-p:id', to: "home#show", via: :get
end

app/models/page_rate.rb
class PageRate < ActiveRecord::Base
  belongs_to :page
  belongs_to :member
  #validates :phone, presence: true
  
  attr_accessor :name, :email, :phone, :address, :message

  #喜欢/IP/PV数据 typo = [ip pv]
  def self.increment_rate_count(typo, page_id, amount = 1)
    self.incremented_rate_count(typo, page_id)
  end

  def self.decrement_rate_count(typo, page_id, amount = -1)
    self.incremented_rate_count(typo, page_id)
  end

  def self.incremented_rate_count(typo, page_id, amount = 1)
    PageRate.transaction do
      ks = self.find_by(id: page_id)
      return if ks.nil?
      case typo
      when 'ip'
        ks.ip_count = ks.ip_count.to_i + amount
      when 'pv'
        ks.pv_count = ks.pv_count.to_i + amount
      else
        raise "incorrect typo, typo should has value of [ip pv]"
      end
      ks.save!
    end
  end

end

app/controllers/page_rates_controller.rb
class PageRatesController < ApplicationController
  before_filter :authenticate_user!, only: [:index]
  before_action :set_page_rate, only: [:show, :edit, :update, :destroy]

  # GET /page_rates
  # GET /page_rates.json
  def index
    @page_rates = PageRate.all
  end

  # GET /page_rates/1
  # GET /page_rates/1.json
  def show
    @page = @page_rate.page
    @pr_qrcode_path = get_qrcode(@page_rate)
  end

  # GET /page_rates/new
  def new
    @page_rate = PageRate.new
  end

  # GET /page_rates/1/edit
  def edit
  end

  # POST /page_rates
  # POST /page_rates.json
  def create
    page = Page.find(page_rate_params[:page_id])
    member = Member.find_by(phone: page_rate_params[:phone])
    member ||= Member.create!(user_id: page.user_id, name: page_rate_params[:name], email: "#{page_rate_params[:phone]}@qq.com", phone: page_rate_params[:phone], password: '000000', password_confirmation: '000000')
    
    unless @page_rate = PageRate.find_by(page_id: page.id, member_id: member.id)
      @page_rate = PageRate.new(page_rate_params)
      @page_rate.member_id = member.id
      @page_rate.ip_count = 1
      @page_rate.pv_count = 1
    end

    respond_to do |format|
      if @page_rate.save
        format.html { redirect_to @page_rate, notice: t('.notice') }
        format.json { render action: 'show', status: :created, location: @page_rate }
      else
        format.html { render action: 'new' }
        format.json { render json: @page_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_rates/1
  # PATCH/PUT /page_rates/1.json
  def update
    respond_to do |format|
      if @page_rate.update(page_rate_params)
        format.html { redirect_to @page_rate, notice: 'Page rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_rates/1
  # DELETE /page_rates/1.json
  def destroy
    @page_rate.destroy
    respond_to do |format|
      format.html { redirect_to page_rates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_rate
      @page_rate = PageRate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_rate_params
      params.require(:page_rate).permit(:page_id, :member_id, :name, :phone)
    end

    def get_qrcode(page_rate)
      qr_dir = File.join(Rails.root, 'public', 'pr_qrcode')
      FileUtils.mkdir_p qr_dir
      png_path = File.join(qr_dir, "#{page_rate.id}.png")
      if File.exist? png_path
        #FileUtils.rm png_path
      else
        url = get_url(page_rate.page, page_rate.id)
        qr = RQRCode::QRCode.new( url, :size => 6, :level => :h )
        png = qr.to_img # returns an instance of ChunkyPNG
        png.resize(120, 120).save(png_path)
      end
      return "/pr_qrcode/#{page_rate.id}.png"
    end
end

app/helpers/page_rates_helper.rb
module PageRatesHelper
end

app/views/page_rates/_custom_baidu_share.html.erb
<div class="bdsharebuttonbox" data-tag="share_1">
  <a class="bds_copy" data-cmd="copy"></a>
  <a class="bds_mshare" data-cmd="mshare"></a>
  <a class="bds_weixin" data-cmd="weixin"></a>
  <a class="bds_sqq" data-cmd="sqq"></a>
  <a class="bds_tqq" data-cmd="tqq"></a>
  <a class="bds_douban" data-cmd="douban"></a>
  <a class="bds_taobao" data-cmd="taobao"></a>
  <a class="bds_qzone" data-cmd="qzone" href="#"></a>
  <a class="bds_tsina" data-cmd="tsina"></a>
  <a class="bds_baidu" data-cmd="baidu"></a>
  <a class="bds_renren" data-cmd="renren"></a>
  <a class="bds_tqf" data-cmd="tqf"></a>
  <a class="bds_tieba" data-cmd="tieba"></a>
  <a class="bds_tsohu" data-cmd="tsohu"></a>
  <a class="bds_meilishuo" data-cmd="meilishuo"></a>
  <a class="bds_more" data-cmd="more">更多</a>
  <a class="bds_count" data-cmd="count"></a>
</div>

<script>
  window._bd_share_config = {
    common : {
      bdText : '<%= page.title %>', 
      bdDesc : '<%= page.title %>', 
      bdUrl : '<%= get_url(page, page_rate.id)%>',   
      bdPic : '<%= page.image %>'
    },
    share : [{
      "bdSize" : 24
    }],
    slide : [{     
      bdImg : 0,
      bdPos : "right",
      bdTop : 100
    }],
    image : [{
      viewType : 'list',
      viewPos : 'top',
      viewColor : 'black',
      viewSize : '16',
      viewList : ['qzone','tsina','huaban','tqq','renren']
    }],
    selectShare : [{
      "bdselectMiniList" : ['qzone','tqq','kaixin001','bdxc','tqf']
    }]
  }
  with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?cdnversion='+~(-new Date()/36e5)];
</script>

app/views/page_rates/_form.html.erb
<%= simple_form_for(@page_rate) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :page %>
    <%= f.association :member %>
    <%= f.input :rate_count %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/page_rates/edit.html.erb
<h1>Editing page_rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @page_rate %> |
<%= link_to 'Back', page_rates_path %>

app/views/page_rates/index.html.erb
<h1>Listing page_rates</h1>

<table>
  <thead>
    <tr>
      <th>Page</th>
      <th>Member</th>
      <th>Rate count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @page_rates.each do |page_rate| %>
      <tr>
        <td><%= page_rate.page %></td>
        <td><%= page_rate.member %></td>
        <td><%= page_rate.rate_count %></td>
        <td><%= link_to 'Show', page_rate %></td>
        <td><%= link_to 'Edit', edit_page_rate_path(page_rate) %></td>
        <td><%= link_to 'Destroy', page_rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page rate', new_page_rate_path %>

app/views/page_rates/new.html.erb
<h1>New page_rate</h1>

<%= render 'form' %>

<%= link_to 'Back', page_rates_path %>

app/views/page_rates/show.html.erb
<div class="content">
  <div class="page">
    <article>
      <h2>你的分享链接为：</h2>
      <div class="well">
        <b><%=link_to get_url(@page,  @page_rate.id),  get_url(@page,  @page_rate.id) %></b>
      </div>
      请将上面的分享链接复制给你的朋友！
      <%= render partial: 'custom_baidu_share', locals: {page: @page, page_rate: @page_rate} %>
      <h2>或者通过手机扫描下面的二维码：</h2>
      <div class="well">
       <%= image_tag @pr_qrcode_path %>
      </div>
      想要查看被分享的次数，请在左边的搜索框输入你的<b>手机号码</b>进行查询。<br/><br/><br/>
      <p>返回: &nbsp; <%=link_to @page.title, get_url(@page, @page_rate.id) %></p>
    </article>
  </div>
</div>