config/routes.rb
Tanmer::Application.routes.draw do
  resources :page_images do 
    collection {post :upload}
  end

  mount Ckeditor::Engine => '/ckeditor'
  get "members/index"
  get "members/show"
  get "members/edit"
  get "members/update"
  get "members/destroy"
  resources :page_rates

  devise_for :members
  resources :books
  resources :keystores

  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks"}
  #match '/users/auth/:provider/callback', to: "omniauth_callbacks#all", via: :get

  # devise_scope :users do
  #   get "/auth/:provider/callback" => "omniauth_callbacks_controller#all"
  # end

  resources :users do
    resources :pages
    resources :members
  end

  #match home search/case special path
  match '/search(/page/:page)', to: "home#search", via: :get, as: 'search'
  match '/case(/page/:page)', to: "home#case", via: :get, as: 'case'
  #tag
  match '/users/:user_id/tag/:tag(/page/:page)', to: "pages#tag", via: :get, as: 'tag'

  #short url
  match '/u/:user_id', to: "pages#index", via: :get
  #match '/:user_id/:id', to: "pages#show", via: :get

  match '/p/u:user_id-p:id', to: "home#show", via: :get
end

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController
  before_action :set_user, only: [:index, :show, :search]

  def index
    #render text: request.remote_ip and return
    @book = Book.new #联系我们
  end

  def show
    #{"controller"=>"home", "action"=>"show", "user_id"=>"2", "id"=>"6a1bb3ca98"}
    #render text: params and return 
    #set page
    if params[:id] =~ /^\d+$/i
      @page = Page.find_by(id: params[:id])
    end
    @page ||= Page.find_by(short_title: params[:id])
    not_found if params[:id] && @page.nil?

    #increment rate count
    Keystore.increment_value_for("page:#{@page.id}:view_count")
    # PV(访问量)：即Page View, 即页面浏览量或点击量，用户每次刷新即被计算一次。
    # UV(独立访客)：即Unique Visitor,访问您网站的一台电脑客户端为一个访客。00:00-24:00内相同的客户端只被计算一次。 --- 暂不做统计
    # IP(独立IP)：指独立IP数。00:00-24:00内相同IP地址只被计算一次。
    Page.increment_rate_count('pv', @page.id)
    if IpAddress.new_ip?(request.remote_ip, @page.id)
      Page.increment_rate_count('ip', @page.id)
      if params[:pr_id]
        PageRate.increment_rate_count('ip', params[:pr_id])
      end
    end
    
    if params[:pr_id]
      PageRate.increment_rate_count('pv', params[:pr_id])
    end

    #extend URL redirect
    respond_to do |format|
      if !@page.extend_url.blank? && @page.typo == 'single'
          format.html { redirect_to  @page.extend_url }
      else
        format.html { render action: 'show' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  #案例中心
  def case
    @user = User.first
    @pages = Page.where(user_id: @user.id).order("updated_at desc").page(params[:page])
  end

  def search
    if params[:search] =~ /^\s*1\d{10}\s*$/ #member phone search
      member = Member.find_by(phone: params[:search])
      if member
        redirect_to user_member_path(member.user.id, member), notice: "查询到号码为#{params[:search].gsub(/\d{4}$/, '****')}的会员信息如下..."
        return
      end
    end

    @users = User.where('typo = "seed" and name like ?', "%#{params[:search]}%") if current_user
    @users ||= []
    
    @pages = if current_user 
      current_user.pages.search(params[:search]).order("updated_at desc").page(params[:page])
    elsif @user
      @user.pages.search(params[:search]).order("updated_at desc").page(params[:page])
    else
      Page.search(params[:search]).order("updated_at desc").page(params[:page])
    end
    @pages ||= []
    
  end

  private
    def set_user
      @user = User.find_by(id: params[:user_id])
      @user ||= current_user
    end

end

app/views/home/case.html.erb
<%= render file: 'pages/index.html.erb' %>

app/views/home/index.html.erb
<% title Keystore.value_for("site_title") %>

<div class="content">
  <div class="page">
    <article>
      <div class="page-header page-header-resume">

        <%= image_tag asset_path('qrcode.png') %>
        <h1 class="main-color"><%= Keystore.value_for("site_title") %></h1>
        <p class="lead">商家开展产品二维码营销的最便捷手段.</p>
      </div><!-- end page-header -->
      <div class="row">
        <div class="col-md-6">
          <ul class="fa-ul">
            <li><i class="fa-li fa fa-envelope"></i> <a href="mailto:sw@rxy123.com">master@inruby.com</a></li>
            <li><i class="fa-li fa fa-phone"></i> 028-83388967</li>
            <li><i class="fa-li fa fa-mobile-phone"></i> 180 8081 0818</li>
          </ul>
        </div><!-- end col-md-6 -->
        <div class="col-md-6">
          <ul class="fa-ul">
            <li><a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=77632132&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:77632132:41" ></a></li>
            <li><a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=77632132&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:77632132:41" ></a></li>
            <li><a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=741502756&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:741502756:41" ></a></li>
          </ul>
        </div><!-- end col-md-6 -->
      </div><!-- end row -->
      <hr class="margin-top-10" />
      <h4>为什么选择<%= Keystore.value_for("site_title") %>？</h4>
      <dl>
        <dt><i class="fa fa-rub"></i> 不用建站，不用购买服务器 --- 产品就在云端！</dt>
        <dd>若企业按照传统方式开展二维码营销，则必须要搭建一个企业站点，购买服务器并保障服务的正常运行，这个过程费钱费力。而我们的产品二维码系统完全基于云计算架构，空间内存无限扩展，保证你的产品24小时在云端。</dd>
        <dt><i class="fa fa-qrcode"></i> 产品二维码动态生成</dt>
        <dd>通过我们自主研发的产品二维码生成系统，动态生成产品二维码，并对每一个产品进行唯一标示，保障产品追踪，和二维码的线下使用.</dd>
        <dt><i class="fa fa-star"></i> O2O一条龙服务</dt>
        <dd>在网上添加产品，动态生成二维码；同时我们提供统一的二维码打印设备和贴码技术，实现线上二维码雨线下产品的无缝结合.</dd>
        <dt><i class="fa fa-shopping-cart"></i> 在线预定，快速获取消费订单！</dt>
        <dd>商家通过二维码营销，打通多渠道网络流量入口； 用户可以通过二维码扫描产品并在线预定，快速实现流量转化！</dd>
      </dl>
      <ul class="list-unstyled post-meta">
        <li class="text-center"><a id="online-order" href="#none" class="btn btn-default btn-lg btn-block" data-html="true" data-toggle="popover" title="" data-original-title="联系我们">联系我们，马上开启二维码营销</a></li>
      </ul>
      <h3>应用场景</h3>
      <table class="table table-bordered table-hover">
        <tbody>
          <tr>
            <td><div class="text-center"><i class="fa fa-barcode fa-2x"> </i> <br/> 产品二维码 </div></td>
            <td><div class="text-center"><i class="fa fa-bullseye fa-2x"> </i> <br/> 产品防伪追踪 </div></td>
            <td><div class="text-center"><i class="fa fa-cloud fa-2x"> </i> <br/> 产品增强展示 </div></td>
            <td><div class="text-center"><i class="fa fa-tasks fa-2x"> </i> <br/> 营销效果检测 </div></td>
          </tr>
          <tr>
            <td><div class="text-center"><i class="fa fa-book fa-2x"> </i> <br/> 企业手机海边 </div></td>
            <td><div class="text-center"><i class="fa fa-comments fa-2x"> </i> <br/> 产品微信营销 </div></td>
            <td><div class="text-center"><i class="fa fa-phone fa-2x"> </i> <br/> 企业手机网站 </div></td>
            <td><div class="text-center"><i class="fa fa-fire fa-2x"> </i> <br/> 移动电子商务 </div></td>
          </tr>
          <tr>

            <td colspan="3"> </td>
            <td><div class="text-right"> <a href="/case">@查看案例展示</a> </div></td>
          </tr>
        </tbody>
      </table>
    </article>
  </div><!-- end page -->
</div><!-- end content -->

<div id="order-form">
  <%= simple_form_for(@book) do |f| %>
    <%= f.error_notification %>
    <div class="form-group">
      <%= f.association :page, as: :hidden, input_html: { value: 1} %>
      <%= f.input :phone %>
      <%= f.input :message %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, input_html: {class: 'btn btn-primary'} %>
    </div>
  <% end %>
</div>

app/views/home/search.html.erb
<% title '搜索' + params[:search] %>

<% content_for :side_bar do %>

<% end %>

<div class="page">
  <article>
    <div class="page-header">
      <h1>搜素结果</h1>
      <p class="lead">共搜索到应用<strong><%= @users.try(:size) %></strong>个，页面<strong><%= @pages.try(:size) %></strong>个</p>
    </div><!-- end page-header -->
    <table class="table table-hover">
      <thead>
        <tr>
          <th>资源包</th>
          <th>描述</th>
          <th>应用数</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% next if user == current_user %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.description %></td>
            <td><%= user.pages.size %></td>
            <td>
              <div id="follow_form_<%= user.id %>">
                <% if current_user.following?(user) %>
                  <%= render partial: 'users/unfollow', locals: {other_user: user} %>
                <% else %>
                  <%= render partial: 'users/follow', locals: {other_user: user} %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">&nbsp;</td>
          <td><%= link_to user_path(current_user.id) do %>
                      <i class="fa fa-qrcode"></i>  我的订阅
                    <% end %></td>
        </tr>
      </tbody>
    </table>

  </article>
</div>
<div class="content">
  <div class="portfolio-wrapper">
    <% @pages.each do |page| %>
      <div class="card film art">
        <%= link_to get_url(page), class: 'thumb' do %>
          <img src="<%= page.image %>" alt="<%= page.title %>" title="<%= page.title %>" />
          <span class="overlay"><span class="fa fa-search"></span></span>
        <% end %>
        <div class="card-body">
          <h2><%= link_to page.title, get_url(page) %></h2>
          <p><%= page.description %></p>
          <p><%= link_to '阅读更多', get_url(page) %></p>
        </div><!-- end card-body -->
      </div><!-- end card -->
    <% end %>
  </div><!-- end portfolio-wrapper -->
  <div class="pagination-wrapper">
    <%= will_paginate @pages %>
  </div>
</div><!-- end content -->

app/views/home/show.html.erb
<% title @page.title %>
<% meta_keywords  [@page.title, '探码'].join('|')%>
<% meta_description @page.description %>

<% content_for :side_bar do %>
  <li>
    <img src="<%= @page.qrcode %>" alt="<%= get_url(@page) %>" title="<%= @page.title %>" class="qrcode-img" />
    <p class="text-center">扫描本产品二维码，在手机上查看~</p>
  </li>
<% end %>

<div class="content">
  <div class="page">
    <article>
      <div class="page-header">
        <h1> <%= @page.title %></h1>
        <p class="lead"><%= @page.description %></p>
      </div><!-- end page-header -->
      <div class="row">
        <div class="col-md-12">
          <ul class="list-unstyled post-meta">
            <% unless @page.properties.blank? %>
              <li><span class="fa fa-th"></span>型号： <%= @page.properties %> </li>
            <% end %>
            <% unless @page.amount.blank? %>
              <li><span class="fa fa-sort-amount-asc"></span>库存： <%= @page.amount %> </li>
            <% end %>
            <% unless @page.price.blank? %>
              <li><span class="fa fa-cny"></span>价格： <%= @page.price %> </li>
            <% end %>
            <!-- <li class="text-center"><a id="online-order" href="#none" class="btn btn-default btn-lg btn-block" data-html="true" data-toggle="popover" title="" data-original-title="在线预定">在线预定</a></li>
            <li class="text-center"><a id="online-rate" href="#none" class="btn btn-default btn-lg btn-block" data-html="true" data-toggle="popover" title="" data-original-title="有奖转发">有奖转发</a></li> -->
          </ul><!-- end post-meta -->
        </div><!-- end col -->
      </div>

      <%= raw @page.content %>
      <% if user_signed_in? && current_user.id == @page.user_id %>
        <hr/>
        <%= link_to '修改', edit_user_page_path(current_user, @page), class: 'btn btn-primary btn-large' %>  &nbsp;&nbsp;
        <%= link_to '删除', [current_user, @page], method: :delete, data: { confirm: '删除以后无法恢复，确定要删除吗?' }, class: 'btn btn-grey btn-large' %>
      <% end %>
    </article>
  </div><!-- end page -->
</div><!-- end content -->

<%= render partial: 'pages/order_rate_form' %>