config/routes.rb
Tanmer::Application.routes.draw do
  resources :page_images do 
    collection {post :upload}
  end

  mount Ckeditor::Engine => '/ckeditor'
  get "members/index"
  get "members/show"
  get "members/edit"
  get "members/update"
  get "members/destroy"
  resources :page_rates

  devise_for :members
  resources :books
  resources :keystores

  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks"}
  #match '/users/auth/:provider/callback', to: "omniauth_callbacks#all", via: :get

  # devise_scope :users do
  #   get "/auth/:provider/callback" => "omniauth_callbacks_controller#all"
  # end

  resources :users do
    resources :pages
    resources :members
  end

  #match home search/case special path
  match '/search(/page/:page)', to: "home#search", via: :get, as: 'search'
  match '/case(/page/:page)', to: "home#case", via: :get, as: 'case'
  #tag
  match '/users/:user_id/tag/:tag(/page/:page)', to: "pages#tag", via: :get, as: 'tag'

  #short url
  match '/u/:user_id', to: "pages#index", via: :get
  #match '/:user_id/:id', to: "pages#show", via: :get

  match '/p/u:user_id-p:id', to: "home#show", via: :get
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, raw(msg), :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">导航切换</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '首页', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to '退出', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to '登录', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to '修改密码', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to '注册', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? and current_user.has_role? :admin %>
  <li><%= link_to '用户管理', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<% if @page && !@page.extend_url.blank? && params[:controller] == "home" %>
  <%= raw @page.content %>
<% else %>
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : Keystore.value_for('site_title') %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tanmer" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <link href="//libs.baidu.com/fontawesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    
    <script src="http://open.web.meitu.com/sources/xiuxiu.js" type="text/javascript"></script>
    <script type="text/javascript">
      window.onload=function(){
        xiuxiu.embedSWF("altContent",1,"100%","100%");
        /*第1个参数是加载编辑器div容器，第2个参数是编辑器类型，第3个参数是div容器宽，第4个参数是div容器高*/
        xiuxiu.setUploadURL("http://115.29.195.174:3000/page_images");//修改为上传接收图片程序地址
        xiuxiu.setUploadType(2);
        xiuxiu.setUploadDataFieldName("page_image[image]");
        xiuxiu.onInit = function ()
        {
          //xiuxiu.loadPhoto("<%#= @page_image.image.url %>");//修改为要处理的图片url
        }
        xiuxiu.onUploadResponse = function (data)
        {
          //alert("上传响应" + data); 可以开启调试
        }
        xiuxiu.onClose = function (id)
        {
          //关闭模态框
          $('.modal.in').modal('hide');
          $('.modal-backdrop.in').hide();
        }
      }
    </script>

  </head>
  <body>
    <% if @page && @page.typo == 'single' && params[:controller] == 'home' && params[:action] == 'show' %>
      <%= raw @page.content %>
      <%= render partial: 'pages/order_rate_form' %>
    <% else %>
      <div class="wrapper">
        <div class="row">
          <div class="col-md-3 sidebar">
            <div class="navbar" role="navigation">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#rebound-navbar-collapse"><span class="fa fa-bars"></span> 导航</button>
                <% if u = (current_user || @user) %>
                  <a href="/users/<%= u.id %>" class="navbar-brand"><%= u.name %></a>
                <% else %>
                  <a href="/" class="navbar-brand main-color"><i class="fa fa-qrcode fa-2x"></i></a>
                <% end %>
                <p class="brand-text"><%= Keystore.value_for("site_title") %></p>
              </div><!-- end navbar-header -->
              <div class="collapse navbar-collapse" id="rebound-navbar-collapse">
                <ul class="nav navbar-nav">
                  <li class="title">菜单</li>
                  <li class="active"><a href="/">关于</a></li>
                  <%= render 'layouts/navigation_links' %>
                </ul>
                <ul class="nav navbar-nav">
                  <% if user_signed_in? %>
                    <li class="title">管理</li>
                     <li>
                      <%= link_to new_user_page_path(current_user.id), class: "active" do %>
                        <i class="fa fa-plus"></i>  添加页面
                      <% end %>
                    </li>
                    <li>
                      <%= link_to user_pages_path(current_user.id) do %>
                        <i class="fa fa-list"></i>  页面列表
                      <% end %>
                    </li>
                    
                    <li>
                      <%= link_to books_path do %>
                        <i class="fa fa-book"></i>  查看订单
                      <% end %>
                    </li>
                    <li>
                      <%= link_to user_members_path(current_user) do %>
                        <i class="fa fa-users"></i>  查看会员
                      <% end %>
                    </li>
                    <li>
                      <%= link_to user_pages_path(current_user.id, qrcode: true) do %>
                        <i class="fa fa-qrcode"></i>  打印二维码
                      <% end %>
                    </li>
                    
                  <% else %>
                    <li>
                      <%= link_to case_path do %>
                        <i class="fa fa-list"></i>  案例中心
                      <% end %>
                    </li>
                  <% end %>
                </ul>
                <%= yield(:side_bar) %>
                <form class="navbar-form" role="search" action="/search">
                  <div class="input-group">
                    <input name="search" type="text" class="form-control" placeholder="标题/产品/电话号码..." value="" />
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="submit"><span class="fa fa-search"></span></button>
                    </span>
                  </div><!-- end input group -->
                </form><!-- end navbar-form -->
              </div><!-- end navbar-collapse -->
            </div><!-- end navbar -->
          </div><!-- end col -->
          <div class="col-xs-12 col-sm-12 col-md-9">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div><!-- end col -->
        </div><!-- end row -->
      </div><!-- end wrapper -->
      
      <footer class="hidden-xs">
        <p class="pull-left">&copy; 版权所有 2014. <%= Keystore.value_for("site_title") %>.</p>
      </footer>
    <% end %>
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript">
      
      $(document).ready(function() {
        
        $('.dropdown-toggle').dropdown();
        var $container = $('.portfolio-wrapper');
        $container.imagesLoaded( function(){
          $container.isotope({
            itemSelector : '.card',
            layoutMode : 'fitRows'
          });
        });
        
        // Needed functions
        var getColWidth = function() {
          var width,
          windowWidth = $(window).width();
          if( windowWidth <= 480 ) {
            width = Math.floor( $container.width() );
          } else if( windowWidth <= 768 ) {
            width = Math.floor( $container.width() );
          } else {
            width = Math.floor( 250 );
          }
          return width;
        }

        function setWidths() {
          var colWidth = getColWidth();
          $container.children().css({ width: colWidth });
        }

    
        $(window).smartresize(function() {
          setWidths();
          $container.isotope({
            masonry: {
              columnWidth: getColWidth()
            }
          });
        });
        
        $('.filter-portfolio li a').click(function(){
          $('.filter-portfolio li.active').removeClass('active');
          $(this).parent('li').addClass('active');
          var selector = $(this).attr('data-filter');
          $container.isotope({
            filter: selector,
            masonry: {  }
          });
          return false;
        });
        // update columnWidth on window resize
        $(window).smartresize(function(){
          $container.isotope({
            // update columnWidth to a percentage of container width
            masonry: {  }
          });
        });
        
      });
      
    </script>

    <script type="text/javascript">
      $(document).ready(function() {
        $('.dropdown-toggle').dropdown();
        $('[data-toggle=tooltip]').tooltip();
        //$('[data-toggle=popover]').popover({html:true});

        $('#online-order').popover({
            html:true,
            placement:'top',
            content:function(){
              return $('#order-form').html();
            }
        });
        $('#online-rate').popover({
            html:true,
            placement:'top',
            content:function(){
              return $('#rate-form').html();
            }
        });

      });
    </script>

  </body>
</html>
<% end %>